- name: "Configure webserver with dynamiclly load the vars file which contain package name"
  hosts: all
  vars_files:
          - "{{ ansible_facts['distribution'] }}.yml"
  tasks:
   - name: "Installing the package in server"
     package: 
      name: "{{ package_name }}"
      state: present
   - name: "Copying the webpages to the server"
     template:
             src: "index.html"
             dest: /var/www/html/
   - name: "start the web service inside the server"
     service:
             name: "{{ package_name }}"
             state: started

